"""update_enum

Revision ID: eac5f0be0f99
Revises: b9d83e1f03d1
Create Date: 2024-12-22 22:02:51.585337

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eac5f0be0f99'
down_revision: Union[str, None] = 'b9d83e1f03d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE request_stats SET r_priority = 'HIGH' WHERE r_priority = 'CRITICAL'")
    op.execute("ALTER TYPE requestpriorityenum RENAME TO requestpriorityenum_old;"
               "CREATE TYPE requestpriorityenum AS ENUM('LOW', 'MEDIUM', 'HIGH');"
               "ALTER TABLE request_stats ALTER COLUMN r_priority DROP DEFAULT;"
               "ALTER TABLE request_stats ALTER COLUMN r_priority TYPE requestpriorityenum USING r_priority::text::requestpriorityenum;"
               "DROP TYPE requestpriorityenum_old;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
