name: sts-playground

services:
  minio:
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: MINIO_AK
      MINIO_ROOT_PASSWORD: MINIO_SK
      MINIO_REGION: eu-west-1
    command: server --console-address ":9001" /data
    logging:
      driver: json-file
      options:
        max-size: "10m"