name: sts-playground

services:
  gateway:
    image: nginx:1.23.3
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  minio:
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: MINIO_AK
      MINIO_ROOT_PASSWORD: MINIO_SK
      MINIO_REGION: eu-west-1
    command: server --console-address ":9001" /data
    logging:
      driver: json-file
      options:
        max-size: "10m"

  sts:
    build:
      context: ../.
    restart: always
    depends_on:
      - minio
    healthcheck:
      test: curl -f http://sts/hc || exit 1
      interval: 20s
      timeout: 2s
      retries: 3
      start_period: 2s
    environment:
      BUCKETS__THUMBNAIL-SMALL__SIZE: "100x100"
      BUCKETS__THUMBNAIL-SMALL__ALIAS: small
      BUCKETS__THUMBNAIL-MEDIUM__SIZE: "500x500"
      BUCKETS__THUMBNAIL-MEDIUM__ALIAS: medium
      S3: "http://MINIO_AK:MINIO_SK@minio:9000/eu-west-1/images"